<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Cache\Cache;
use Cake\ORM\TableRegistry;

/**
 * Dashborad Controller
 *
 * @property \App\Model\Table\DashboradTable $Dashborad
 */
class WebsiteController extends AppController
{
    public $paginate = [
        'limit' => 12
    ];
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->Auth->allow();
    }

    /**
     * Index method
     *
     * @return void
     */
    public function index()
    {
        $this->viewBuilder()->layout('website');
        $All_moviesTbl =  TableRegistry::get('movies');
        $all_movies = $All_moviesTbl->find();
        $this->set('all_movies',$this->paginate($all_movies));
    }
    public function details($id)
    {
        $this->viewBuilder()->layout('website');
        $moviesTbl =  TableRegistry::get('movies');
        $movie = $moviesTbl->find();
        $movie->where(['NUM'=>$id]);
        $this->set(compact('movie'));

    }
    public function searchMovie($category=null)
    {
        $this->viewBuilder()->layout('website');
        $moviesTbl =  TableRegistry::get('movies');
        $movies = $moviesTbl->find();
        // check string
        if(!empty($category))
        {
            $movies->where(['CATEGORY'=>$category]);
        }
        else
        {
            $input = $this->request->data;
            if(is_numeric($input['string']))
                $movies->where(['YEAR'=>$input['string']]);
            else
                $movies->where(['ORIGINALTITLE LIKE'=>$input['string'].'%']);

            if($input['directors'])
                $movies->where(['DIRECTOR LIKE'=>$input['directors']]);

            if($input['movie_type'])
                $movies->where(['MOVIE_TYPE LIKE'=>$input['movie_type']]);
        }
         $this->set(compact('movies'));
    }

    public function searchMovieCategory($category)
    {
        $this->viewBuilder()->layout('website');
        echo $category;
    }


}
